name: Build & Deploy to Cloudflare worker

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: cd app && yarn install && cd ..
      - run: yarn workspace app build
        env:
          CI: true
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: worker
          wranglerVersion: '1.13.0'
